src/py_scripts/fc_run.py

- Allow Falcon to work on a single node without SGE
- Support assembly of <4 kb reads

some small changes

---

README.md

Make it even easier to find documentation

create link to manual

---

src/py_scripts/fc_run.py

possible fix

---

examples/fc_run_LG.cfg
examples/fc_run_arab.cfg
examples/fc_run_dmel.cfg
examples/fc_run_ecoli.cfg
examples/fc_run_ecoli_2.cfg
src/py_scripts/fc_run.py
src/py_scripts/fc_run_LG.py

This wasn't actually merged. (See #69.)

ConfigParser

---

examples/fc_run_LG.cfg
examples/fc_run_arab.cfg
examples/fc_run_dmel.cfg
examples/fc_run_ecoli.cfg
examples/fc_run_ecoli_2.cfg

I think these are needed, yes?

--output_dformat for daligner

---

src/py_scripts/fc_run.py

Improve 5d03f282db18c9f4b3141d677e3f37e9ff1fe987
"allow relative paths in input_fofn_fn"
by avoiding timestamp updates when input_fofn did not change.

proper dependency for abs fofn

---

.gitmodules

Switch to this:
* https://github.com/pb-cdunn/FALCON-module/wiki/Installation
* https://github.com/pb-cdunn/FALCON-module

remove submodules

---

.gitmodules

Switch to this:
* https://github.com/pb-cdunn/FALCON-module/wiki/Installation
* https://github.com/pb-cdunn/FALCON-module

rm submodules

---

src/py_scripts/fc_consensus.py

This lets my fast test pass, which will soon become the gating test for FALCON-integrate.

more config for fc_consensus.py

---

setup.py
src/py_scripts/fc_run.py

I had a good Travis run with this!
* https://travis-ci.org/pb-cdunn/FALCON-integrate

minor fixes for debugging

---

src/py/mains/run.py

Update fc_run.py
re: PacificBiosciences#106
@rlleras, We do not have integration tests for SLURM, so please be understanding if we break this in the future.

add support for SLURM job submission

---

src/py/mains/run.py

resolves #109 
```
$ ls sge_log/
prepare_pdb.sh-build_pdb-build_pdb.o3708857                   rp_00001.sh-m_00001_preads-m_00001_preads.o3708860
prepare_pdb.sh-build_pdb-build_pdb.po3708857                  rp_00001.sh-m_00001_preads-m_00001_preads.po3708860
rj_49681d6b.sh-d_49681d6b_preads-d_49681d6b_preads.o3708859   run_falcon_asm.sh-falcon-falcon.o3708861
rj_49681d6b.sh-d_49681d6b_preads-d_49681d6b_preads.po3708859  run_falcon_asm.sh-falcon-falcon.po3708861
```
The `.po` files are actually empty because we use `-j y` with **qsub**.

prepend script base to job-name

---

src/py/mains/graph_to_contig.py

fix a typo

---

.gitignore
src/py/mains/run.py
src/py/mains/run_LG.py

Instead, expect everything to be available in the environment.
FALCON-integrate/FALCON-make can help set that up.
resolves #143

Stop using virtualenv directly.

---

src/py/mains/run.py

On some systems, there may be an advantage to running daligner on db files in /tmp. This is a re-working (by cdunn) of an idea from @yunfeiguo. See discussion at end of #152.
The new config is:
```
[General]
use_tmpdir = True
```
I have not measured any improvement on our fileservers, but it could be significant elsewhere.

use_tmpdir

---

src/py/mains/run.py
src/py/mains/run_LG.py

This addresses #153 and #143, resolving #156.

short-term way to pass some env-vars into qsub jobs

---

src/py/mains/run.py

lock rsync calls

---

src/py/mains/run.py
src/py/run_support.py

I am refactoring so that we can have a new version of fc_run.py for pbsmrtpipe. It's basically cut-and-paste.

refactoring run.py

---

src/py/mains/run.py

keep using global type_type in wait_for_file()

---

src/py_scripts/fc_run.py

restore the file previously deleted accdidentally

---

src/py/mains/run.py

We were having collisions with only 8 bytes of randomness.
Jason, This fix works for me. Is this what you had in mind?

Unique job_ids

---

src/py/functional.py
src/py/mains/run.py
test/test_functional.py

Mv xform here from FALCON-pbsmrtpipe. This is a kind of dependency injection.
* https://github.com/PacificBiosciences/FALCON-pbsmrtpipe/commit/c92cf5c1eaa765dd382763f5c574730aa6023318

Minor refactoring.

---

src/py/run_support.py

Fail if LA4Falcon fails

---

src/py/run_support.py

This will tell us how much time each command is taking. (There might be a better way with bash, but this way works.)
I plan to do some profiling on fc_sense, if I can get a line-profiler working:
* https://zapier.com/engineering/profiling-python-boss/

Finer timing

---

setup.py
src/py/mains/consensus.py
src/py/multiproc.py

These are minor changes that can make it easier to use gperftools someday.
The Python LineProfiler can be helpful, but for the most part Python multiprocessing does not work well with gperfools. Oh, well. See #231.

Prep for profiling

---

src/py/mains/run.py

This has no impact on large test-cases, but my small one is 6x faster (10s vs. 60s). We should actually notice that speed-up in TravisCI (for FALCON-integrate, not FALCON).
Note that `updateFreq` means nothing. Within `refresh()` the sleep_time increases arithmetically (up to 1) already.

Progressive wait_time

---

src/py/bash.py
src/py/mains/run.py
src/py/run_support.py

* Rm exit-files at end-of-task for LOCAL. (Already happens for SGE.)
* Try to fix race condition when job_done exists but job_done+.exit does not yet. (See by user in #263.)

Consistent exit files

---

src/py/run_support.py

Can help find errors error. Just a warning.

Report unused config

---

src/py/mains/run.py

Jim said there might be a problem of jobs being killed somehow on the Pod, so we wait forever on them.
I don't know quite what is going on, but I've made changes to let us detect whether a job is still making progress. The idea is simple:
* Every batch job will include a background process which writes to a progress-file periodically (every 60sec).
* The falcon job thread (i.e. not pypeflow) will `stat` that progress-file (mtime) while it waits for the done/exit files. If the progress-file does not change in 10min (arbitrary number), then we consider the job finished. (Success or failure is determined elsewhere.)
* Since we do not know when a queued job has begun, we first block on the *existence* of the progress-file. (We could timeout on that someday too, but that's a separate issue.) …

Wait on progress

---

falcon_kit/bash.py
falcon_kit/run_support.py

Allow us to specify --min_idt
Resolves #291
https://bugzilla.nanofluidics.com/show_bug.cgi?id=31554

fc_ovlp_to_graph_option

---

falcon_kit/bash.py

DBsplit with -a always

---

falcon_kit/mains/consensus.py
falcon_kit/mains/dedup_a_tigs.py
falcon_kit/mains/ovlp_filter.py
falcon_kit/mains/ovlp_stats.py
falcon_kit/mains/ovlp_to_graph.py
src/c/falcon.c

Also, remove 2 obsolete flags.

Help defaults

---

falcon_kit/mains/run.py
falcon_kit/mains/run1.py
falcon_kit/util/system.py

os.symlink(), not 'ln -s'

---

falcon_kit/functional.py
src/c/falcon.c

fixes PacificBiosciences/FALCON-integrate#44

Use g_best_score in declared block

---

falcon_kit/mains/run0.py
falcon_kit/mains/run1.py
falcon_kit/run_support.py
falcon_kit/stats_preassembly.py

This is not the pbsmrtpipe *Report*, since that requires the `pbreports` modules, which requires `matplotlib` and other crap. This is only a simple JSON file of everything we need for the *Report*. Really, it's all the users care about. It's very cheap to produce.

Stats for pre-assembly

---

falcon_kit/mains/run1.py

Pretty simple change. ("yield" didn't work because we need to adjust the concurrency between refresh calls.)

Accept Workflow obj in run1

---

falcon_kit/bash.py
falcon_kit/functional.py
falcon_kit/mains/run0.py
falcon_kit/mains/run1.py
test/test_functional.py

Addresses #411, but does not yet fix it. (The fix will be in a different repo.)

Pass nblock to get_daligner_tasks()

---

falcon_kit/functional.py
falcon_kit/stats_preassembly.py
falcon_kit/util/io.py
test/test_stats_preassembly.py

* https://jira.pacificbiosciences.com/browse/SAT-105

preassembled_seed_fragmentation

---

falcon_kit/mains/ovlp_to_graph.py

The updated case is more robust against such case as one of the
duplicated one will be removed. The repeat-bridge removal logic
will apply later if the such edges in the assembly graph is indeed
caused by repeats/chimera.

more robust edge filtering for the cases two subreads generating the same chimera connection

---

falcon_kit/mains/run1.py
falcon_kit/run_support.py

corresponding PR for https://github.com/PacificBiosciences/pypeFLOW/pull/28

corresponding PR for pypeFLOWpr28

---

falcon_kit/bash.py

Fix from Jason and msc51
