PacificBiosciences/FALCON

- src/py_scripts/fc_run.py
change  "example: HGAP.py HGAP_run.cfg" to  "usage: fc_run.py fc_run.cfg"
> Misleading usage

- src/c/DW_banded.c
- src/c/common.h
- src/c/falcon.c
- src/c/kmer_lookup.c
We still have these 3 to address:
```
src/c/falcon.c: In function ‘get_cns_from_align_tags’:
src/c/falcon.c:522:28: warning: ‘bb’ may be used uninitialized in this function [-Wmaybe-uninitialized]
cns_str[index] = bb;
^
src/c/falcon.c:367:26: warning: ‘base’ may be used uninitialized in this function [-Wmaybe-uninitialized]
unsigned int base;
^
src/c/falcon.c:360:34: warning: ‘t_pos’ may be used uninitialized in this function [-Wmaybe-uninitialized]
if (delta > msa_array[t_pos]->max_delta) {
```
> fix warnings

- src/py_scripts/fc_run.py
`set -e` is good for stopping the job early. However, we still wait for the `.done` file, since that is the only way we have to receive a message from a distributed job.
With this change, the job will still create the `.done` file always, but it will remove a new `.done.incomplete` file *only* if there was no error. That lets us stop quickly.
TODO: Possibly, we need to trap exceptions somewhere and delete running jobs.
For local jobs, we turn job failures into exceptions, which helps debugging though it is not strictly necessary.
TODO: When we are comfortable that we handle failures well, we can raise the Exception optionally, so the local flow will match the distributed flow by default.
> Notify if 'done' job is incomplete

- src/py_scripts/fc_run.py
aklammer@ says:
> 423, 424 – All logging should be in UTC, and include appropriate context
* http://bugzilla.nanofluidics.com/show_bug.cgi?id=26699
* http://stackoverflow.com/questions/12139648/python-logging-specifying-converter-attribute-of-a-log-formatter-in-config-file
* http://stackoverflow.com/questions/6321160/python-logging-how-to-set-time-to-gmt
* https://docs.python.org/2/library/logging.html#logging.Formatter.formatTime
> use GMT for logging

- .travis.yml
- setup.py
- src/c/ext_falcon.c
- src/py/FastaReader.py
- src/py/falcon_kit.py
- src/py_scripts/fc_consensus.py
- src/py_scripts/fc_run.py
- travis.sh
By using the standard distutils.Extension, we can load the shared module more reliably. Then, `ctypes.CDLL` can operate on the `.so` (or `.dylib`) which was loaded by the extension module.
This is passing in my repo:
* https://travis-ci.org/pb-cdunn/FALCON/builds
We just need somebody (mhsieh?) to enable it for PacificBiosciences/FALCON.
Also, all it does is build right now, which is better than nothing. But we can run unit-tests as we add them. You have to run 'nosetests' on the virtualenv installation because many modules depend on the shared libraries, but that's working fine.
> Proper ext_modules; Travis CI

- src/py/mains/ovlp_to_graph.py
After examining with whole genome alignments and the assembly graphs to understand why contigs break even though there are indeed sequence information linking different contigs, adding a couple heuristics to improve the sequence ovelaps to assembly graph to contig performance.  It is now possible generate a CHM1 assembly up to N50>25Mb and Max Contig Size > 100Mb with the recent P6 data. Whether such rules are general enough for other genomes is still under investigation.
> New layout rules for oval_to_graph.py

- src/py/mains/run.py
rlleras wrote:
```
Had to come up with a simple way to fix the "Missing interpreter" error SLURM was giving with FALCON 0.3 that wouldn't break other schedulers. This should make FALCON stable for any future releases, and is compatible with Python 3.0+ as well, so no need to update code if/when Python version is updated.
Update run.py
Add SCANCEL support
Add support for SLURM jobs to automatically cancel failed jobs in event of FALCON failure.
fix indentation and loss of break
Update run.py
```
closes FALCON#181
> Fix SLURM support for FALCON

- src/py/mains/run.py
- src/py/run_support.py
Minor.
Soon, `create_daligner_tasks()` will include LAsort lines with associated daligner lines, to avoid some network copies. Also, it will balance job-size better, I think.
> refactoring run.py

- src/py/functional.py
- src/py/mains/run.py
- src/py/run_support.py
- test/HPCdaligner_synth0.sh
- test/test_functional.py
Combine `LAsort` w/ `daligner` jobs
This should reduce some network copying and might balance the jobs
better too.
Also, a nice functional test.
This works for me, both locally and in SGE. It definitely copies less data. I have not tested runtime impact, but it will affect NFS users more than us (on lustre).
> Combine `LAsort` w/ `daligner` jobs

- src/py/mains/run.py
Added support for PBS torque.
`job_type = torque` can now be used in the CFG file.
Here is an example of what to place in the CFG file
```
job_type = torque
sge_option_da = -l nodes=1:ppn=16:compute,walltime=4:00:00
sge_option_la = -l nodes=1:ppn=16:compute,walltime=4:00:00
sge_option_pda = -l nodes=1:ppn=16:compute,walltime=4:00:00
sge_option_pla = -l nodes=1:ppn=16:compute,walltime=4:00:00
sge_option_fc = -l nodes=1:ppn=16:compute,walltime=4:00:00
sge_option_cns = -l nodes=1:ppn=16:compute,walltime=4:00:00
```
> Update run.py to support Torque qsub

- .gitignore
- src/py/mains/run.py
- src/py/run_support.py
This will let us alter FALCON-pbsmrtpipe without worrying about anything in
FALCON, but also without having to release a change to pbsmrtpipe
simultaneously (since that repo requires pull-requests).
Because we sometimes drive FALCON from pbsmrtpipe, and because all options in pbsmrtpipe need specific documentation and inputting by the user, we need to stop requiring options which are not used in the pbsmrtpipe workflow.
I had planned to do this *after* simplifying how options are passed from pbsmrtpipe, but I am not going to win the argument over there.
> Rename get_dict() to get_dict_from_old_falcon_cfg()

- src/py/mains/run.py
- src/py/run_support.py
We no longer symlink anything after a daligner run. Instead,
we wait for all to finish; then we symlink the minimum set needed.
This resolves a problem discussed privately with @dgordon562.
Tested on simulated data with 50 blocks, 50 merge jobs, and 338 daligner jobs. (No typos.) It took a bit longer than usual (normally 1 minute for this 5kbp simulation), but it finished with a perfect assembly. I verified that it symlinked *exactly* 2500 (50*50) files into the m_* directories.
Currently, it does not rm old *.las files from the daligner runs, but it does rm intermediate *.las from the m_* merge directories.
> Avoid too many ln/mkdir

- src/py/mains/run.py
This is a favor to @dgordon562. His SGE names are truncated when
printed. We simply drop some leading zeroes and use hexadecimal.
If the number of jobs gets huge, we just lose the leading zeroes
and fixed width, no problem. But if you have > 64k jobs, you have
bigger problems.
> Reduce typical job_uid

- src/py/mains/run.py
- src/py/run_support.py
It's better to pass that via ovlp_DBsplit_options directly.
We might have to fix this is some examples too.
> Stop using length_cutoff_pr for ovlp_DBsplit_option

- src/py/bash.py
- src/py/mains/run.py
- src/py/run_support.py
* Generate scripts independent of workflow, runnable in any
directory.
* Use templates for scripts where possible, for transparency.
* Generate done/exit wrappers in a generic way, decoupled from sub-scripts.
* Use shebang lines for sub-scripts, so they will show up in **top**.
* Separate Consensus task from Merge.
* Separate DB2Falcon task.
* Identify more inputs/outputs, for better restarts.
* Drop 'tmpdir' (until we are more specific about input/outputs).
This will dramatically simplify pbsmrtpipe integration, as well as pypeflow improvements.
> Some refactoring

- src/py/bash.py
- src/py/mains/run.py
- src/py/run_support.py
- src/py/util/io.py
These minor changes/clarifications work fine with both pypeflow and pbsmrtpipe.
The most important change is to provide `preads4falcon.fasta` and the list of `*.las` to run_falcon_asm, so it can make fewer assumptions.
> Run falcon asm

- src/py/mains/run.py
- src/py/run_support.py
As a *separate* change in pypeFLOW, we can ignore ignoreOnFailure if there are not successful jobs yet when the first one fails. In that case, we can just fail early.
But this change to FALCON is independent of that one. So we can merge this first. We can update FALCON-integrate with *both* changes. I'll post the pypeFLOW PR soon...
> Stop all jobs on failure

- src/py/mains/run.py
- src/py/run_support.py
This has an esoteric advantage. But .ini is still fine for most users.
Also, I've changed build_rdb/pdb to remove the existing DB whenever the task is actually run. There was a case where it could be skipped. (Remember: We do not look at return-codes. So if a fasta is altered, it may appear to be "already in" the db. And we look at timestamps to decide whether a task needs to be run.)
> Json logging

- falcon_kit/FastaReader.py
- falcon_kit/bash.py
- falcon_kit/functional.py
- falcon_kit/mains/calc_cutoff.py
- falcon_kit/run_support.py
- setup.py
- test/test_functional.py
- travis.sh
Based on `DBstats -b1`.
A bit messy for now, and calculated in twice 2 different steps,
since we do not want to add another pbsmrtpipe task. But **DBstats**
should be super-fast even on a large genome.
> Calc length_cutoff

- falcon_kit/bash.py
- falcon_kit/run_support.py
**DBdust** shows very little improvement for Lambda, but it might help in extreme cases. Eventually, we can turn this on by default, but it could cause us to lose physical homopolymers. For now it needs more experimenting testing.
To activate:
dust = true
The defaults for `pa_DBdust_option` seem fine. I've tried some others, with no improvement.
> dust and pa_DBdust_option

- falcon_kit/functional.py
- test/HPCdaligner_synth0.sh
- test/test_functional.py
If the merge job fails, then we might need to re-run the whole step.
(Note: If we run in a tmp-dir always, then we make *every* step atomic.
Then, we will not need this change at all.)
Handle both '&&' style and ';' style. And add a test for each.
This should help with #349, but eventually it will be better to merge in `/tmp` and consider the whole task either done or not done.
> Do not rm intermediate .las files

- falcon_kit/mains/run.py
Hi,
I run Faclon on a SGE cluster, and I have problems with jobs failing in Eqw state.
The problem comes from the fact that the cluster is configured with 'unix_behavior' for the 'shell_start_mode'. With this configuration, all scripts submitted to the cluster must have a shebang definition to run correctly.
Here's a little patch to always add a shebang to generated scripts. It is almost the same as for the slurm scheduler.
> SGE: fix Eqw error when 'shell_start_mode' option is set to 'unix_behavior'

- falcon_kit/bash.py
- falcon_kit/functional.py
- falcon_kit/mains/run.py
- falcon_kit/mains/run1.py
- falcon_kit/run_support.py
- test/test_functional.py
This is now a better implementation than before. We symlink all NFS files from the work-dir into a run-dir under `/tmp`. Then, only after completion, we *move* the non-symlinks from the tmp run-dir back to the NFS work-dir. This should completely solve #350.
However, we still do not copy (or rsync) the DB  or other inputs into `/tmp`. That would take a bit of work. According to @dgordon562 in #345, the daligner jobs do not need this, but **LA4Falcon** could benefit from a DB in `/tmp` because it uses non-sequential access of the DB. That is TODO.
For another example of weird problems when runnning in NFS that are solved when running in `/tmp`, see this comment:
* https://github.com/PacificBiosciences/blasr/issues/232#issuecomment-216943603
Someday, we can add some **LAcheck** calls for …
> Implement `use_tmpdir`

- falcon_kit/mains/run.py
- falcon_kit/mains/run1.py
> The e. coli run test fails due to wrong patterns for the las files in the `las.fofn` file

- falcon_kit/mains/run1.py
- falcon_kit/run_support.py
* PypeTask functions must be module-global, since they are executed on the remote host.
* Loggers must exist, since these module can be imported by a different program on the remote host.
> Minor changes

- falcon_kit/mains/run1.py
This will turn on the new thing for everyone. I had thought to make it somehow configurable, but I like it enough that I want to switch to it completely. I will do much more testing before a new release anyway. Before then, we also have to look at the default `pwatcher_type`, a setting MJ added last week.
> Use new simple_pwatcher_bridge.

- falcon_kit/bash.py
- falcon_kit/run_support.py
When falcon_greedy is turned on, 'LA4Falcon -fog'
instead of 'LA4Falcon -fo' will be used.
> Add falcon_greedy option to config
